import React from 'react';
import { UvmComponentType, AiResponse, SimulationStep } from '../types';

interface InfoPanelProps {
  component: UvmComponentType;
  data: AiResponse | null;
  loading: boolean;
  simulationStep?: SimulationStep | null;
}

const InfoPanel: React.FC<InfoPanelProps> = ({ component, data, loading, simulationStep }) => {
  // 1. Simulation Mode (Highest Priority)
  if (simulationStep) {
    return (
      <div className="h-full flex flex-col overflow-hidden bg-gray-900/30">
         <div className="p-4 border-b border-indigo-500/30 bg-indigo-900/10 flex justify-between items-center">
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <span className="text-indigo-400">Step {simulationStep.id + 1}:</span> {simulationStep.label}
          </h2>
          <span className="text-xs bg-indigo-900/50 border border-indigo-500/30 px-2 py-1 rounded text-indigo-200">
            Walkthrough Mode
          </span>
        </div>
        
        <div className="flex-1 overflow-y-auto p-6 space-y-6 scroll-smooth">
          {/* Explanation Section */}
          <section className="prose prose-invert max-w-none">
             <div className="whitespace-pre-wrap text-gray-200 leading-relaxed font-sans text-sm md:text-base border-l-4 border-indigo-500 pl-4">
               {simulationStep.description}
             </div>
          </section>
  
          {/* Code Section */}
          <section className="bg-[#1e1e1e] rounded-lg border border-indigo-500/30 overflow-hidden shadow-xl">
            <div className="bg-[#2d2d2d] px-4 py-2 text-xs text-indigo-300 font-mono border-b border-gray-700 flex justify-between">
              <span>Simulation Snippet</span>
              <span>SystemVerilog</span>
            </div>
            <pre className="p-4 overflow-x-auto text-sm font-mono text-blue-300">
              <code>{simulationStep.codeSnippet}</code>
            </pre>
          </section>
        </div>
      </div>
    );
  }

  // 2. Loading State
  if (loading) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-gray-400 space-y-4 animate-pulse">
        <div className="w-12 h-12 border-4 border-t-uvm-accent border-gray-700 rounded-full animate-spin"></div>
        <p>Asking Gemini about {component}...</p>
      </div>
    );
  }

  // 3. Empty State
  if (!data) {
    return (
      <div className="h-full flex items-center justify-center text-gray-500">
        <p>Select a block in the diagram to learn more.</p>
      </div>
    );
  }

  // 4. Standard AI Data View
  return (
    <div className="h-full flex flex-col overflow-hidden">
      <div className="p-4 border-b border-gray-700 bg-gray-800/50 flex justify-between items-center">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <span className="text-uvm-accent">#</span> {component}
        </h2>
        <span className="text-xs bg-gray-700 px-2 py-1 rounded text-gray-300">Generated by Gemini 2.5</span>
      </div>
      
      <div className="flex-1 overflow-y-auto p-6 space-y-6 scroll-smooth">
        {/* Explanation Section */}
        <section className="prose prose-invert max-w-none">
           <div className="whitespace-pre-wrap text-gray-300 leading-relaxed font-sans text-sm md:text-base">
             {data.explanation}
           </div>
        </section>

        {/* Code Section */}
        <section className="bg-[#1e1e1e] rounded-lg border border-gray-700 overflow-hidden shadow-xl">
          <div className="bg-[#2d2d2d] px-4 py-2 text-xs text-gray-400 font-mono border-b border-gray-700 flex justify-between">
            <span>{component.toLowerCase().replace(" ", "_")}.sv</span>
            <span>SystemVerilog</span>
          </div>
          <pre className="p-4 overflow-x-auto text-sm font-mono text-green-400">
            <code>{data.codeSnippet}</code>
          </pre>
        </section>
      </div>
    </div>
  );
};

export default InfoPanel;